kind: Service
apiVersion: v1
metadata:
  name: dqm-square-k8
  namespace: dqm
spec:
  selector:
    app: dqmsquare-mirror-server-testbed
  ports:
    - port: 8084
      targetPort: 8084
      name: dqmsquare-mirror-server-testbed
    - port: 18084
      targetPort: 18084
      name: dqmsquare-mirror-server-testbed-mon
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-server-testbed
  namespace: dqm
  labels:
    app: dqmsquare-mirror-server-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-server-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-server-testbed
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: dqmsquare-mirror-server-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:latest #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "server"]
        args: []
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        ports:
          - containerPort: 8084
            protocol: TCP
            name: crabserver
          - containerPort: 18084
            protocol: TCP
            name: crabserver-mon
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-parser-testbed
  namespace: dqm
  labels:
    app: dqmsquare-mirror-parser-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-parser-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-parser-testbed
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: dqmsquare-mirror-parser-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:latest #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "parser"]
        args: []
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-robber-testbed
  namespace: dqm
  labels:
    app: dqmsquare-mirror-robber-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-robber-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-robber-testbed
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: dqmsquare-mirror-robber-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:latest #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "robber"]
        args: []
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "4Gi"
            cpu: "800m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
          - name: robot-secrets
            mountPath: /etc/robots
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
      - name: robot-secrets
        secret:
          secretName: robot-secrets
---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: dqmsquare-mirror-robber-oldruns-testbed
  namespace: dqm
  labels:
    app: dqmsquare-mirror-robber-oldruns-testbed
spec:
  selector:
    matchLabels:
      app: dqmsquare-mirror-robber-oldruns-testbed
  replicas: 1
  template: # This is the pod template
    metadata:
      labels:
        app: dqmsquare-mirror-robber-oldruns-testbed
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: dqmsquare-mirror-robber-oldruns-testbed
        image: registry.cern.ch/cmsweb/dqmsquare_mirror:latest #imagetag
        command: ["./dqmsquare_k8_wrapper.sh", "robber_oldruns"]
        args: []
        resources:
          requests:
            memory: "2Gi"
            cpu: "400m"
          limits:
            memory: "3Gi"
            cpu: "800m"
        volumeMounts:
          - mountPath: /cephfs/testbed
            name: dqmsquare-mirror-pvc-testbed
          - name: robot-secrets
            mountPath: /etc/robots
      volumes:
      - name: dqmsquare-mirror-pvc-testbed
        persistentVolumeClaim:
          claimName: dqmsquare-mirror-pvc-testbed
          readOnly: false
      - name: robot-secrets
        secret:
          secretName: robot-secrets
